### ISSUE TITLE
Opting for Relative units in CSS

### ISSUE THREAD

**Issue by kessie2862** [akezeth/Portfolio-setup-and-mobile-first#4]
I suggest you opt for **_relative_** units for the most part of the project because,

- [ ] **_Absolute_** units are useful in situations where you need to precisely control the size or positioning of elements on the page, regardless of the size of the viewport or device.

- [ ] **_Relative_** units are useful because they allow you to create responsive layouts that adapt to different screen sizes and device types.

**Comment by akezeth** [comment]
Thanks for your positive feedback. I have revised my code as per your recommendation.
